name: Build extensions

env:
  solution: src/luau.visualstudio.sln

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: nuget restore
        run: nuget restore ${{ env.solution }}
      - name: Build
        run: msbuild ${{ env.solution }} /p:configuration:Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
      - name: Upload grammar extension
        uses: actions/upload-artifact@v3
        with:
          name: luau.visualstudio.grammar.vsix
          path: src/luau.visualstudio.grammar/bin/Release/luau.visualstudio.grammar.vsix
          retension-days: 5
      - name: Upload lsp extension
        uses: actions/upload-artifact@v3
        with:
          name: luau.visualstudio.lsp.vsix
          path: src/luau.visualstudio.lsp/bin/Release/luau.visualstudio.lsp.vsix
          retension-days: 5
